[Appearance]
icon_theme=Papirus-Dark
style=Oxygen
custom_palette=false
standard_dialogs=default
color_scheme_path=

[Fonts]
general="MesloLGS Nerd Font,10,-1,5,50,0,0,0,0,0"
fixed="MesloLGS Nerd Font,10,-1,5,50,0,0,0,0,0"
