# Force adw-gtk3-dark theme for GTK and Libadwaita
GTK_THEME=adw-gtk3-dark
ADW_DEBUG_COLOR_SCHEME=prefer-dark
QT_QPA_PLATFORM=wayland;xcb
QT_QPA_PLATFORMTHEME=qt6ct
QT_STYLE_OVERRIDE=Oxygen
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
