# ==============================================================================
# Variables & Default Applications
# ==============================================================================

# Super / Logo key
set $mod Mod4

# Vim-style direction keys
set $left h
set $down j
set $up k
set $right l

# Preferred Terminal (Foot - Wayland Native)
set $term foot

# Preferred Launcher & Menus
set $menu fuzzel
set $clipboard fuzzel-cliphist
set $powermenu fuzzel-powermenu
set $screenshot screenshot-tool

# Typography
font pango:Terminess Nerd Font 10
