# ==============================================================================
# Theme & Aesthetics (Defqon.1 Weekend Warrior - Industrial Dark 1px Borders)
# ==============================================================================

# 1px Sharp Window Borders
default_border pixel 1
default_floating_border pixel 1
hide_edge_borders none

# Window Gaps & Padding
gaps inner 6
gaps outer 0
smart_gaps off
smart_borders off

# Color definitions (Defqon.1 Industrial Palette)
# class                 border    backgr    text      indicator child_border
client.focused          #e05561   #181a20   #e4e5e8   #f38d41   #e05561
client.focused_inactive #2d313d   #121317   #7d8597   #2d313d   #2d313d
client.unfocused        #1e2029   #121317   #5c6370   #1e2029   #1e2029
client.urgent           #ff4757   #181a20   #ff4757   #ff4757   #ff4757
client.placeholder      #121317   #121317   #e4e5e8   #121317   #121317
