# ==============================================================================
# Waybar Status Bar Integration
# ==============================================================================

bar {
    swaybar_command waybar
}
